#!/bin/sh
#
# Copyright (c) 2015 Google Inc.
#
# This is a pre-push hook that allows the user to run the unit tests
# before uploading a CL for review.

run_UnitTests() {
	save_dir=`pwd`
        status=0
        valid=0
	exec < /dev/tty
	while [ $valid -eq 0 ] ; do
 	  read -p "Run unit tests? [y/n] " choice
          case "$choice" in
	    n|N ) valid=1 ;;
	    y|Y ) valid=1; cd crosperf; ./run_tests.sh; status=$? ;
		  cd $save_dir;;
	    * ) echo "Must choose y or n."
	  esac
        done
        if [ $status -ne 0 ]
	then
	    exit $status
	fi
}

run_UnitTests

exit 0
